"""The committed payload fixtures are a contract shared with the frontend.

The fixtures are generated by ``tests/generate_fixtures.py``. These tests fail
when a payload gains, loses, or retypes a key without the fixture being
regenerated, which is what keeps ``frontend/src/types.ts`` honest.
"""

import json
from pathlib import Path

import pytest
from generate_fixtures import build_payloads, type_name

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"
FIXTURE_NAMES = (
    "load",
    "analyze",
    "options",
    "inspect_readout",
    "inspect_deembed",
    "inspect_contribution",
    "ablate",
)


def read_fixture(name: str) -> dict:
    return json.loads((FIXTURE_DIR / f"{name}.json").read_text(encoding="utf-8"))


def read_schema() -> dict:
    return json.loads((FIXTURE_DIR / "schema.json").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def live_schema(tmp_path_factory):
    directory = tmp_path_factory.mktemp("fixtures") / "checkpoint"
    payloads = build_payloads(directory)
    return {
        name: {key: type_name(value) for key, value in payload.items()}
        for name, payload in payloads.items()
    }


def test_live_payloads_match_the_committed_schema(live_schema):
    assert live_schema == read_schema()


def test_every_fixture_is_committed(live_schema):
    assert set(live_schema) == set(FIXTURE_NAMES)


def test_sample_fixtures_match_the_schema(live_schema):
    for name in FIXTURE_NAMES:
        payload = read_fixture(name)
        assert set(payload) == set(live_schema[name]), name
